on:
  push:
    branches: [master]

jobs:
  create-feedstock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Locate pr meta.yaml
        id: meta
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
            then
              echo "::set-output name=META_YAML::${changed_file}";
              exit 0
            fi
          done
          exit 1 # Fail - meta.yaml required

      - name: Print meta
        run: |
          echo  "${{ steps.meta.outputs.META_YAML }}"
