name: Run recipe
on:
  release:
    branches: [ master ]
    types: [ published ]
jobs:
  run-recipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Download bakeries.yaml
        id: download-bakeries
        run: |
          curl https://raw.githubusercontent.com/pangeo-forge/bakery-database/main/bakeries.yaml -o ${GITHUB_WORKSPACE}/bakeries.yaml
      - name: Locate meta.yaml
        id: meta
        run: |
          echo "::set-output name=META_YAML::$(git ls-files '*meta.yaml')"
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          latest: true
      - name: Process release recipe
        if: ${{ steps.meta.outputs.META_YAML != null }}
        uses: pangeo-forge/recipe-prefect-action@pangeonotebook-2021.07.17_prefect-0.14.22_pangeoforgerecipes-0.5.0
        with:
          path_to_meta_yaml: ${{ steps.meta.outputs.META_YAML }}
          path_to_bakeries_yaml: bakeries.yaml
          prune: true
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          PREFECT__CLOUD__AUTH_TOKEN: ${{ secrets.PREFECT__CLOUD__AUTH_TOKEN }}
          PREFECT_PROJECT_NAME: ${{ secrets.PREFECT_PROJECT_NAME }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          COMMENT_ID: ${{  steps.latest_release.outputs.id  }}
